export const FOLDER_TYPE = {
  USER: 'USER',
  SHARED: 'SHARED',
  UNASSEMBLED: 'UNASSEMBLED',
  EXECUTOR: 'EXECUTOR',
  AUTHOR: 'AUTHOR',
  ALL: 'ALL',
  ROOT_USER: 'ROOT_USER',
  ROOT_SHARED: 'ROOT_SHARED',
}
